### ISSUE TITLE
No sound 

### ISSUE THREAD

**Issue by Xanaxus** [Spotifyd/spotifyd#984] opened 2021-07-26 01:46 UTC
**Description**

I am unable to  hear any music, I have tried to switch from `alsa` to `pulsesound`, also  tried out `pipewire-alsa`. But neither of them seemed to work.

**To Reproduce**

1. Go to config file and use alsa as the 'backend'

**Expected behavior**

Music must be heard when I try to  play a song

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```
@Suzan ~> aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
samplerate
    Rate Converter Plugin Using Samplerate Library
speexrate
    Rate Converter Plugin Using Speex Resampler
jack
    JACK Audio Connection Kit
oss
    Open Sound System
pipewire
    PipeWire Sound Server
pulse
    PulseAudio Sound Server
speex
    Plugin using Speex DSP (resample, agc, denoise, echo, dereverb)
upmix
    Plugin for channel upmix (4,6,8)
vdownmix
    Plugin for channel downmix (stereo) with a simple spacialization
default
    Default ALSA Output (currently PulseAudio Sound Server)
sysdefault:CARD=PCH
    HDA Intel PCH, ALC295 Analog
    Default Audio Device
front:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    Front output / input
surround21:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    2.1 Surround output to Front and Subwoofer speakers
surround40:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    4.0 Surround output to Front and Rear speakers
surround41:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    4.1 Surround output to Front, Rear and Subwoofer speakers
surround50:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    5.0 Surround output to Front, Center and Rear speakers
surround51:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    5.1 Surround output to Front, Center, Rear and Subwoofer speakers
surround71:CARD=PCH,DEV=0
    HDA Intel PCH, ALC295 Analog
    7.1 Surround output to Front, Center, Side, Rear and Woofer speakers
hdmi:CARD=PCH,DEV=0
    HDA Intel PCH, HDMI 0
    HDMI Audio Output
hdmi:CARD=PCH,DEV=1
    HDA Intel PCH, HDMI 1
    HDMI Audio Output
hdmi:CARD=PCH,DEV=2
    HDA Intel PCH, HDMI 2
    HDMI Audio Output
hdmi:CARD=PCH,DEV=3
    HDA Intel PCH, HDMI 3
    HDMI Audio Output
hdmi:CARD=PCH,DEV=4
    HDA Intel PCH, HDMI 4
    HDMI Audio Output
usbstream:CARD=PCH
    HDA Intel PCH
    USB Stream Output
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS:  Manjaro
- Spotifyd:  spotifyd 0.3.2
- cargo:   cargo 1.53.0

**Comment by JojiiOfficial** [comment] 2021-07-28 17:30
Could you please provide more information/logs. With which parameter did you try to start spotifyd? What is the output of spotifyd? How can we reproduce it?

**Comment by Xanaxus** [comment] 2021-07-30 00:21
Sorry, but I am not sure how to generate the logs using the verbose flag. 

**To Reproduce**

1. Go to config file and use `alsa` as the backend even tried `pulseaudio` as previously mentioned.

**Additional points**
Currently, running a BTRFS file system And running Deepin as my DE

**Comment by JojiiOfficial** [comment] 2021-07-30 17:01
Plesaudio won't work since you haven't compiled spotifyd with the `pulseaudio_backend` feature.
Please try to run `spotifyd --no-daemon --verbose` and paste the output.

**Comment by Xanaxus** [comment] 2021-08-01 07:35
Hi I just redid all the installation and setup it works fine; I hit a snag but fixed it, but I want to make sure I did it right, the config file should be saved as a `.config` from now on rt? Or there are other alternatives?

**Comment by Icelk** [comment] 2021-10-16 19:08
The config file should be located at `~/.config/spotifyd/spotifyd.conf`.

If the issue is resolved, please close the issue :)

**Closed** 2021-11-16 14:38 UTC
Labels: bug
