### ISSUE TITLE
spotifyd doesn't respond to play/pause/next/previous from Bluetooth headphones [macOS]

### ISSUE THREAD

**Issue by nbelakovski** [Spotifyd/spotifyd#1263] opened 2024-02-04 01:49 UTC
**Description**
spotifyd doesn't respond to play/pause or next/back from the controls on my Bluetooth headphones

**To Reproduce**
On Mac, connect bluetooth headphones, start spotifyd, start playing something, trying using Bluetooth headphones controls.

**Expected behavior**
See above

**Logs**
N/A (happy to post some logs if helpful)

**Versions (please complete the following information):**
- OS: macOS Monterey 12.6.9
- Spotifyd: 0.3.5
- cargo: N/A

**Additional context**
Not sure if this is a spotifyd issue or a librespot issue but I figured I'd ask here first. The volume control on the Bluetooth headphones works, but I suppose that's because they're adjusting system volume. I'd suppose that play/pause/etc. turn into some sort of system command that spotifyd would need to register with an listen to?

**Comment by eladyn** [comment] 2024-02-18 13:01
Thank you for the report. This is probably a duplicate of #1032, since we're not able to register as a media playback application without a window.

**Closed by eladyn** 2024-02-18 13:01 UTC
Labels: bug
