### ISSUE TITLE
Spotifyd fails to launch

### ISSUE THREAD

**Issue by massdregs** [Spotifyd/spotifyd#701] opened 2020-10-29 08:52 UTC
**Description**
Spotifyd silently fails to launch, even as a service.

**To Reproduce**

1. Install spotifyd-full-git from AUR with rust
2. Run spotifyd

**Expected behavior**
Launch spotify application

**Logs**
<details><summary>Click to show logs</summary>

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(5), col: 11, at: Some(120), message: "", key: [] } }', src/config.rs:468:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

</details>

**Versions (please complete the following information):**
- OS: Arch Linux, 5.9.1-arch1-1
- Spotifyd: 0.2.24
- cargo: 1.47.0

When installed with pamac, pacman, or yay, there is no ~/.config/spotifyd/spotifyd.conf and /etc/systemd/service/spotifyd.service file

I copied the config file and the service file text from the readme.

**Comment by robinvd** [comment] 2020-10-29 09:53
we recently changed the config format. If youre using the old version please see the old readme https://github.com/Spotifyd/spotifyd/commit/7e346c8f2e4ec09e565b311d130fc91a01a244df#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by slondr** [comment] 2021-01-12 23:07
Should be resolved with v0.2.25 (#716)

Let us know if the issue persists

**Closed by slondr** 2021-01-12 23:07 UTC
Labels: bug

**Comment by blueForestIcarus** [comment] 2021-01-21 04:26
The result of parsing the old config format is still to panic. Surely it should log the offending line, right?
Otherwise the only way to figure what the problem is too search for this github issue.

**Comment by robinvd** [comment] 2021-01-21 09:57
it does say the offending line, but i fully agree that panic messages are not the way to display that
```
# from the error in the issue description
kind: NumberInvalid, line: Some(5), col: 11
```
