### ISSUE TITLE
onevent command does not seem to work

### ISSUE THREAD

**Issue by patrickjane** [Spotifyd/spotifyd#215] opened 2019-03-11 18:12 UTC
It seems like the command given to the `--onevent` option is not executed:

```
spotify@pi3HA:/opt/spotifyd/target/release $ ./spotifyd --no-daemon --onevent "echo xxx >> ./bla"
19:10:06 [INFO] Couldn't find config file, continuing with default configuration.
19:10:06 [INFO] Using software volume controller.
19:10:06 [INFO] No backend specified, defaulting to: alsa.
19:10:13 [INFO] Connecting to AP "....spotify.com:443"
19:10:13 [INFO] Authenticated as "me" !
19:10:13 [INFO] Using alsa sink
19:10:13 [INFO] Country: "DE"
19:10:17 [INFO] Loading track "Promises" with Spotify URI "spotify:track:0YxCz1EpiJPyZoXBB99ZyK"
19:10:18 [INFO] Track "Promises" loaded
^Cspotify@pi3HA:/opt/spotifyd/target/release $ ll
total 11M
drwxr-xr-x   8 spotify spotify 4.0K Mar 11 19:09 .
drwxr-xr-x   3 spotify spotify 4.0K Feb 25 09:54 ..
drwxr-xr-x  78 spotify spotify 4.0K Feb 25 09:35 build
-rw-r--r--   1 spotify spotify    0 Feb 25 09:35 .cargo-lock
drwxr-xr-x   2 spotify spotify  52K Feb 25 14:06 deps
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 examples
drwxr-xr-x 322 spotify spotify  20K Feb 25 09:35 .fingerprint
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 incremental
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 native
-rwxr-xr-x   2 spotify spotify  11M Feb 25 14:06 spotifyd
-rw-r--r--   1 spotify spotify  282 Feb 25 14:06 spotifyd.d
``` 

The file is writable (e.g. executing `echo xxx >> ./bla` manually in the same directory writes the file).

**Comment by SimonPersson** [comment] 2019-03-25 20:39
Hi! So I'm a little bit surprised that you don't get any log output. I get: 
```21:32:16 [INFO] Running ["/home/simon/test.sh"] with environment variables {"PLAYER_EVENT": "start", "TRACK_ID": "1O2SlAUcjIoFFt9vpI3P1i"}```
whenever an event happens.

However, the `--onevent` flag does not run in a shell. This means that your output redirection (`>>`) will not work. Instead, create a script:
```
#!/bin/bash
echo 1 >> /home/simon/yay
```
and supply that as `--onevent`. Don't forget to make it executable.

**Comment by SimonPersson** [comment] 2019-03-25 20:53
I'll close this issue, but feel free to reopen the ticket if it still doesn't work!

**Closed by SimonPersson** 2019-03-25 20:53 UTC

**Comment by patrickjane** [comment] 2019-03-26 10:42
Why did you close the issue? Does `onevent` work for you? The example above should represent a minimal reproducable example, but I understand the redirection does not work. In my configuration however I am actually using a script which is sending messages to MQTT, and it is not beeing executed. 

I've modified the minimal example to use a script, as you suggested, and as expected, it won't work either:

```
spotify@pi3HA:/opt/spotifyd/target/release $ ./spotifyd --no-daemon --onevent /opt/spotifyd/target/release/testscript
11:38:56 [INFO] Couldn't find config file, continuing with default configuration.
11:38:56 [INFO] Using software volume controller.
11:38:56 [INFO] No backend specified, defaulting to: alsa.
11:39:12 [INFO] Connecting to AP "gew1-accesspoint-b-4v6l.ap.spotify.com:443"
11:39:12 [INFO] Authenticated as "patrickjane7" !
11:39:12 [INFO] Using alsa sink
11:39:12 [INFO] Country: "DE"
11:39:12 [INFO] Loading track "Me And My Monkey" with Spotify URI "spotify:track:7hTj4BiAUI2Y65vAyq4j0t"
11:39:12 [INFO] Track "Me And My Monkey" loaded
^Cspotify@pi3HA:/opt/spotifyd/target/release $ ll
total 11M
drwxr-xr-x   8 spotify spotify 4.0K Mar 26 11:38 .
drwxr-xr-x   3 spotify spotify 4.0K Feb 25 09:54 ..
drwxr-xr-x  78 spotify spotify 4.0K Feb 25 09:35 build
-rw-r--r--   1 spotify spotify    0 Feb 25 09:35 .cargo-lock
drwxr-xr-x   2 spotify spotify  52K Feb 25 14:06 deps
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 examples
drwxr-xr-x 322 spotify spotify  20K Feb 25 09:35 .fingerprint
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 incremental
drwxr-xr-x   2 spotify spotify 4.0K Feb 25 09:35 native
-rwxr-xr-x   2 spotify spotify  11M Feb 25 14:06 spotifyd
-rw-r--r--   1 spotify spotify  282 Feb 25 14:06 spotifyd.d
-rwxr-xr-x   1 spotify spotify   30 Mar 26 11:38 testscript
spotify@pi3HA:/opt/spotifyd/target/release $ cat testscript
#!/bin/bash
echo xxx >> ./bla
```

Executing the script manually of course writes the file "bla".

**Comment by SimonPersson** [comment] 2019-03-26 10:53
Yes, sorry, it is working fine for me. What build are you running? Did you compile it yourself? When did you build it?

**Comment by patrickjane** [comment] 2019-03-26 11:12
Yes I compiled it myself. I've compiled commit `2abc392` somewhen in january/february.

So maybe the issue is fixed by using the latest version or using precompiled binaries for raspberry pi.

**Comment by SimonPersson** [comment] 2019-03-26 12:59
Yes, please try to build the latest release. If the problem is still there, feel free to reopen this ticket.
