### ISSUE TITLE
Spotifyd doesn't always register service in dbus

### ISSUE THREAD

**Issue by ahlaw** [Spotifyd/spotifyd#434] opened 2019-11-21 16:09 UTC
Neither qdbus or playerctl list spotifyd as a service in dbus. I think this is the same problem from the closed issue [#276](https://github.com/Spotifyd/spotifyd/issues/276), but the fix did not work for me. I tried both the latest release and building with `dbus_mpris` flag.

**Comment by SirWindfield** [comment] 2019-11-21 17:19
It registers the service because you can send messages using `dbus-send` and they work without any problems. playerctl might expect a property or method that is currently not implemented correctly (or implemented at all) and fails therefore to detect the service. I don't have much time as of recently because university takes up most of my free time now...

I would be happy to have someone who could dig into their code and see what they do to detect the service. IIRC qdbus is just something similar to `dbus-send`, which makes it even weirder that it doesn't work using that CLI.

**Comment by ahlaw** [comment] 2019-11-21 17:56
I tried `dbus-send` and it did not list spotifyd as a service. The command I ran was 
```
dbus-send --system            \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames
```

**Comment by tommady** [comment] 2019-12-21 09:05
hi @ahlaw the spotifyd is not registered in *system* session.
you can use this to find it.
```
dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames
```
```
method return time=1576919053.619598 sender=org.freedesktop.DBus -> destination=:1.31 serial=3 reply_serial=2
   array [
      string "org.freedesktop.DBus"
      string "org.mpris.MediaPlayer2.spotifyd"
      string ":1.31"
      string ":1.28"
   ]
```

**Comment by ahlaw** [comment] 2020-01-13 19:57
Hi, I tried that command and still could not find spotifyd registered. This was with the newest v0.2.23 release using the full binary.

**Comment by thomaslawton91** [comment] 2020-01-15 07:30
I can confirm this issue after having run `dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames`. I'm also not seeing spotifyd as being advertised to playerctl. I have tested with both the full binary and a fully compiled version.

**Comment by sigmonsays** [comment] 2020-01-16 22:16
i've came to this same issue. 

this is empty
`sig@desktop2:~$ dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames |grep -i spotify
`

**Comment by jb55** [comment] 2020-01-16 23:43
Going to pile on here. I tried on `0.2.18`, didn't work. so I updated to `0.2.23` and it still didn't work. `dbus-send --session --dest=org.freedesktop.DBus --type=method_call --print-reply /org/freedesktop/DBus org.freedesktop.DBus.ListNames |grep -i spotify` returns nothing for both of them.

**Comment by jb55** [comment] 2020-01-16 23:53
nevermind, it looks like my distro (nixos) didn't enable the `dbus_mpris` feature

**Comment by sigmonsays** [comment] 2020-01-22 19:55
how does one check if they have dbus_mpris enabled ?

**Comment by SirWindfield** [comment] 2020-01-22 20:28
I don't think that there is currently a way to tell. The logs don't tell you either until an error occurs during registration. Might be a good idea to add some output to `--help` showing the compilation features used.

**Comment by treeshateorcs** [comment] 2020-01-24 02:38
mpris not working here, neither if i build it myyself with the features enabled, nor the archive from the releases page

**Comment by frafall** [comment] 2020-02-02 21:41
Seems to me mpris is not active when I do not have a user/passwd in config file. Once I run with these defined I got initial spotifyd mpris/dbus registration and control worked thru mpris.

My use case is to use spotifyd on a rapsberry with remote control over mqtt (self built mqtt/mpris integration) and the user id should be the one used in the (cell/pc) Spotify client using Spotify Connect. So no user/pass in config file, at least thats what I to do on librespot/raspotify but I would like to swap to spotifyd due to mpris control

Running without user/pass does not seem possible, no dbus registration nor mdns.

Running spotifyd 0.2.24

**Comment by ahlaw** [comment] 2020-02-03 18:41
The `full` build of spotifyd 0.2.24 resolved the issue for me. The `full` build of spotifyd 0.2.23 did not. Good to close this issue?

**Comment by thomaslawton91** [comment] 2020-02-03 20:22
Sorry to come back a little late to this. My issue has also been resolved with the new `full` build.

**Closed** 2020-02-03 20:54 UTC
Labels: bug

**Comment by MatthiasGrandl** [comment] 2020-03-04 16:54
I also can't get it to work. I compiled it with `cargo build --release --features dbus_keyring,dbus_mpris`. 
I am on 0.2.24.

Can't test with the prebuilt binary as I get a library error `error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

**Comment by SirWindfield** [comment] 2020-03-04 22:05
Never have seen your problem before @MatthiasGrandl, maybe some system dependencies are a version behind or you don't have `openssl` installed. 

To be honest, I am not sure if dbus works without specifying a username and password as dbus relies on some Spotify api calls. I can take a look at the weekend though.
