### ISSUE TITLE
Unable to connect to device

### ISSUE THREAD

**Issue by ThomasFoernzler** [Spotifyd/spotifyd#1267] opened 2024-02-20 19:19 UTC
**Description**
The Spotifyd-device is shown in the list, clicking on it initiates the "connecting to device", but in the end it fails

**To Reproduce**
Start spotifyd on device
got to app (webapp, spotify-launcher, android app)
click on connect

**Expected behavior**
music plays from device

**Logs**
<details><summary>Click to show logs</summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("******"), username_cmd: None, password: Some("*********"), password_cmd: None, use_keyring: false, use_mpris: None, dbus_type: None, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: None, volume_controller: None, device: None, control: None, mixer: None, device_name: Some("test"), bitrate: None, audio_format: None, initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: None, autoplay: false, max_cache_size: None } }
Found user shell: Some("/bin/zsh")
No proxy specified
registering event source with poller: token=Token(2147483649), interests=READABLE
Using software volume controller.
registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
signal: Want
signal found waiting giver, notifying
poll_want: taker wants!
signal: Want
signal: Want
Ignoring blacklisted access point ap-gew4.spotify.com:4070
Ignoring blacklisted access point ap-gew4.spotify.com:443
Ignoring blacklisted access point ap-gew4.spotify.com:80
Ignoring blacklisted access point ap-gue1.spotify.com:443
Failed to resolve Access Point: Unable to resolve any viable access points.
Using fallback "ap.spotify.com:443"
Connecting to AP "ap.spotify.com:443"
deregistering event source from poller
signal: Closed
registering event source with poller: token=Token(16777216), interests=READABLE | WRITABLE
Authenticated as "******" !
new Session[0]
Mixing with softvol and volume control: Log(60.0)
new Spirc[0]
Session[0] strong=4 weak=1
canonical_username: posbis
Country: "DE"
new MercuryManager
Input volume 58958 mapped to: 49.99%
new Player[0]
Converting with ditherer: tpdf
Using AlsaSink with format: S16
command=AddEventSender
command=VolumeSet(58958)
subscribed uri=hm://remote/user/posbis/ count=0
registering event source with poller: token=Token(1), interests=READABLE
<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: archlinux
- Spotifyd: 0.3.5
- cargo: 1.71.1
installed via pacman

observed in broswer via console/network logging :

when connecting to play on another "official client":
htttp Options request returns 200
http Post request returns 200

when connecting to play on spotfiyd (tested on archlinux)
htpp Options request resturn 200
http Post request fails 3 times with 502
request: 
```
https://gew4-spclient.spotify.com/connect-state/v1/connect/transfer/from/422eb2b2b8cb851786b514f260954a564f383b34/to/0cd7bb4e8f344fc14e335847c1af15ad4aa94c4e
{"transfer_options":{"restore_paused":"restore"},"page_instance_id":"3f22116a-36fa-4496-88a7-572f47822175","interaction_id":"3a37eccb-0099-4203-a011-217d3c17f4d7"}
```
response:
```
 {"error_type":"INVALID_PLAYER_RESPONSE","message":"Could not parse response from upstream"}
```

**Comment by endofhome** [comment] 2024-02-20 21:36
I'm seeing similar behaviour.
I'm running spotifyd 0.3.3 on Raspbian OS.

I can't connect to the spotifyd device from the Spotify Android app. It was working approximately 9 hours ago.

I see the same HTTP responses using the Spotify in the browser on macOS (200 responses for OPTIONS and 3 x 502 responses for a POST request to `https://gew1-spclient.spotify.com/connect-state/v1/connect/transfer/from/{id1}/to/{id2}`. Payload is the same apart from the values for `page_instance_id` and `interaction_id`.

**Comment by ThomasFoernzler** [comment] 2024-02-21 15:05
Next day, simply works again
maybe a problem on spotify side?

**Comment by endofhome** [comment] 2024-02-21 18:49
I can confirm, it's working again for me too. Looks like Spotify restored service :)

**Comment by eladyn** [comment] 2024-03-15 08:15
That means we probably can close this now as it seems to have been a temporary issue?

**Closed by eladyn** 2024-03-15 08:15 UTC
Labels: bug
