### ISSUE TITLE
armv7 binary Illegal instruction

### ISSUE THREAD

**Issue by zjttoefs** [Spotifyd/spotifyd#53] opened 2017-05-20 12:04 UTC
This is all I get on a raspberry pi (extracted from spotifyd-2017-04-23-armv7.zip):

$ ./spotifyd 
Illegal instruction

I cannot see anything obviously wrong with the binary, but I guess I must be doing something stupid.

**Comment by SimonPersson** [comment] 2017-05-20 12:25
There have been some issues with cross compiling the arm binary. Try compiling it yourself and it should work better.

**Comment by zjttoefs** [comment] 2017-05-20 12:29
Okay, rust has downloaded already and cargo is (slowly) at work...
Are you interested in an updated binary if that ends successfully?

**Comment by SimonPersson** [comment] 2017-05-20 12:31
Great, tell me if you have more issues.

I think the issue is that I haven't managed to get a static build that works on all distributions. Until I manage to get a build that works universally, there's no point in manually uploading them I guess.

**Comment by zjttoefs** [comment] 2017-05-21 15:08
If compiled locally all runs fine, except for minor issues (separate report).

**Comment by SimonPersson** [comment] 2017-06-09 23:51
As you got it working, and as the latest release seems to run on my RPi3, I'll close this issue.

**Closed by SimonPersson** 2017-06-09 23:51 UTC
