### ISSUE TITLE
Add dummy output

### ISSUE THREAD

**Issue by mib4fun** [Spotifyd/spotifyd#78] opened 2017-07-26 20:49 UTC
Hello,

I'm trying to launch to the program on a server for testing purpose.
Is it possible to add a dummy output sound card ?

**Comment by SimonPersson** [comment] 2017-07-26 20:55
You can use `--backend pipe` , that just writes the audio data to stdout. Is that what you are looking for?

**Comment by mib4fun** [comment] 2017-07-26 20:59
yeah just saw that ! Thanks :+1:

**Comment by mib4fun** [comment] 2017-07-26 21:04
I got a weird issue with this.

It's working only for few seconds, max 20 seconds . 
Then the song just repeat by itself

**Comment by SimonPersson** [comment] 2017-07-26 21:11
I *think* that with the pipe backend, spotifyd will just output audio as fast as it can, much faster than actual playback speed. What test are you trying to run? I guess you could just pipe the output into something that will read it slowly if you want to simulate more realistic behaviour.

**Comment by mib4fun** [comment] 2017-07-26 21:19
Hmm... i'm not sure. How do i do that ?
Can you maybe implement kind of the same trick as that: https://github.com/Schnouki/spop/commit/d288ab284a4e7be84a81c182f0dd63afe67d7b81

**Comment by SimonPersson** [comment] 2017-07-26 21:32
I think the difference is that libspotify delivers the stream at playback spead, whereas librespot just dowloads the entire stream at once. Hence, what spop is doing does not work for us.

However, depending on what kind of testing you want to do, you could just load a dummy alsa module on the server, to create an alsa device, no?

**Comment by mib4fun** [comment] 2017-07-26 21:46
Oh okay. 
Yeah, let me try it

**Comment by mib4fun** [comment] 2017-07-26 22:06
Okay. I have this
````
root@dev:~# cat /proc/asound/cards   
 0 [Dummy          ]: Dummy - Dummy
                      Dummy 1
 1 [Loopback       ]: Loopback - Loopback
                      Loopback 1
```

Do you know how i can make it default ?

**Comment by SimonPersson** [comment] 2017-12-19 23:37
I'll close this issue as I can't reproduce it, and changes have been made since the report. Feel free to reopen if the issue remains on the latest commit!

**Closed by SimonPersson** 2017-12-19 23:37 UTC
