### ISSUE TITLE
Panic when trying to run the software

### ISSUE THREAD

**Issue by telometto** [Spotifyd/spotifyd#772] opened 2021-01-15 12:37 UTC
**Description**
Installed with cargo on Fedora 33 Workstation.

**To Reproduce**
`$ spotifyd`
`$ RUST_BACKTRACE=full spotifyd`

**Logs**
<details><summary>Click to show logs</summary>

```
spotifyd --verbose
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("unknown variant `\"alsa\"`, expected one of `alsa`, `portaudio`, `pulseaudio`, `rodio`")', /home/zeno/.cargo/registry/src/github.com-1ecc6299db9ec823/spotifyd-0.2.24/src/config.rs:415:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
RUST_BACKTRACE=full spotifyd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("unknown variant `\"alsa\"`, expected one of `alsa`, `portaudio`, `pulseaudio`, `rodio`")', /home/zeno/.cargo/registry/src/github.com-1ecc6299db9ec823/spotifyd-0.2.24/src/config.rs:415:85
stack backtrace:
   0:     0x5642820a0b50 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h50fd7129fc8c4dfe
   1:     0x5642820c8a9c - core::fmt::write::ha4ab090616b23b8f
   2:     0x564282098685 - std::io::Write::write_fmt::ha42868ce1c3c3ee1
   3:     0x5642820a34c5 - std::panicking::default_hook::{{closure}}::hdfd3387c4c3e6933
   4:     0x5642820a3168 - std::panicking::default_hook::hcfccb51acd2d6402
   5:     0x5642820a3c61 - std::panicking::rust_panic_with_hook::h129019d46564370b
   6:     0x5642820a37a7 - std::panicking::begin_panic_handler::{{closure}}::h4fe11c81158f0272
   7:     0x5642820a100c - std::sys_common::backtrace::__rust_end_short_backtrace::hae84c56702047933
   8:     0x5642820a3709 - rust_begin_unwind
   9:     0x5642820c5f01 - core::panicking::panic_fmt::h3ac7ea34f3a1bc33
  10:     0x5642820c5d23 - core::option::expect_none_failed::hd358c134845a2910
  11:     0x564281c322c3 - spotifyd::config::CliConfig::load_config_file_values::h388bec3c6b0b9db3
  12:     0x564281c43673 - spotifyd::main::h359dc50b263d888a
  13:     0x564281c449d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf991c127eead646a
  14:     0x564281c1c469 - std::rt::lang_start::{{closure}}::hadf70eaac454efa4
  15:     0x5642820a4087 - std::rt::lang_start_internal::h0a9d789f0d6c5cb2
  16:     0x564281c43d92 - main
  17:     0x7f123a5bf1e2 - __libc_start_main
  18:     0x564281c1026e - _start
  19:                0x0 - <unknown>

```
</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**
- OS: Fedora 33 Workstation
- Spotifyd: spotifyd 0.2.24
- cargo: cargo 1.49.0

**Comment by robinvd** [comment] 2021-01-15 13:33
Could you try the newest version of spotifyd 0.3.0?

**Comment by telometto** [comment] 2021-01-15 16:16
> Could you try the newest version of spotifyd 0.3.0?

I have downloaded the [pre-built binary](https://github.com/Spotifyd/spotifyd/releases/download/v0.3.0/spotifyd-linux-full.tar.gz) and copied it into `/usr/local/bin` and it doesn't run at all. If I `mkdir ~/.config/spotifyd/spotifyd.conf` and copy the contents of the [configuration file](https://github.com/Spotifyd/spotifyd#configuration-file) (only changing username and password) I get this error:
```
spotifyd
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: NumberInvalid, line: Some(5), col: 11, at: Some(104), message: "", key: [] } }', src/config.rs:477:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by robinvd** [comment] 2021-01-15 16:58
Ah it was a breaking release as the config changed. There is a pinned issue for it. The new format is in the readme

**Comment by telometto** [comment] 2021-01-16 03:06
> Ah it was a breaking release as the config changed. There is a pinned issue for it. The new format is in the readme

I'm sorry, but I'm new to Linux. Does this mean that I am doing something wrong? I've tried uncommenting `initial_volume = 90` and `proxy = "http://proxy.example.org:8080"`, too, since they also gave me errors but that didn't seem to help, either.

New journalctl:
```
jan. 16 04:05:04 fedora-desk spotifyd[4468]: Loading config from "/home/myuser/.config/spotifyd/spotifyd.conf"
jan. 16 04:05:04 fedora-desk spotifyd[4468]: No proxy specified
jan. 16 04:05:04 fedora-desk spotifyd[4468]: Daemonizing running instance
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Detached from shell, now running in background.
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Using alsa volume controller.
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Checking keyring for password
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Connecting to AP "gew1-accesspoint-e-jk1g.ap.spotify.com:443"
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Authenticated as "myuser" !
jan. 16 04:05:04 fedora-desk spotifyd[4470]: Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by slondr** [comment] 2021-01-16 06:08
This could be a bug in the ALSA backend; I can't reproduce on PulseAudio. Can you post your full config file (remove your login information first)?

**Comment by telometto** [comment] 2021-01-16 19:49
> This could be a bug in the ALSA backend; I can't reproduce on PulseAudio. Can you post your full config file (remove your login information first)?
> 
> EDIT: Wait, just try re-dowloading the newest binary and see if the problem persists. Use the config file you had before you uncommented the proxy stuff.
> There was a bug related to our Rust version that we fixed recently, you may be running into that.

I have downloaded the latest binary and extracted it to `/usr/local/bin`, tried uncommenting and commenting several of the options that give me an erroneous output but the issue still persists. Can you post your config file?

**Comment by TrentSPalmer** [comment] 2021-01-17 13:29
@telometto just now upgrading spotifyd on my RaspberryPi running Arch Linux, after tinkering with the config, I discovered that several of the options now need to be quoted, including the `initial_volume` integer.

**Comment by slondr** [comment] 2021-01-17 15:56
Yes, initial_volume is a string not an integer. This is a bug being fixed in the next major version; in the meantime, just put quotes around the value.

**Comment by telometto** [comment] 2021-01-18 06:55
Here's my config:
```
[global]
# Your Spotify account name.
username = "[REDACTED]"

# Your Spotify account password.
password = "[REDACTED]"

# A command that gets executed and can be used to
# retrieve your password.
# The command should return the password on stdout.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
#password_cmd = "command_that_writes_password_to_stdout"

# If set to true, `spotifyd` tries to look up your
# password in the system's password storage.
#
# This is an alternative to the `password` field. Both
# can't be used simultaneously.
#use_keyring = true

#
# If set to true, `spotifyd` tries to bind to the session dbus
# and expose MPRIS controls. When running headless, without a dbus session,
# then set this to false to avoid binding errors
#
use_mpris = true

# The audio backend used to play the your music. To get
# a list of possible backends, run `spotifyd --help`.
backend = "alsa"

# The alsa audio device to stream audio to. To get a
# list of valid devices, run `aplay -L`,
device = "sysdefault"  # omit for macOS

# The alsa control device. By default this is the same
# name as the `device` field.
control = "sysdefault"  # omit for macOS

# The alsa mixer used by `spotifyd`.
mixer = "PCM"

# The volume controller. Each one behaves different to
# volume increases. For possible values, run
# `spotifyd --help`.
volume_controller = "alsa"  # use softvol for macOS

# A command that gets executed in your shell after each song changes.
on_song_change_hook = "command_to_run_on_playback_events"

# The name that gets displayed under the connect tab on
# official clients. Spaces are not allowed!
device_name = "device_name_in_spotify_connect"

# The audio bitrate. 96, 160 or 320 kbit/s
bitrate = 160

# The directory used to cache audio data. This setting can save
# a lot of bandwidth when activated, as it will avoid re-downloading
# audio files when replaying them.
#
# Note: The file path does not get expanded. Environment variables and
# shell placeholders like $HOME or ~ don't work!
cache_path = "cache_directory"

# If set to true, audio data does NOT get cached.
no_audio_cache = true

# Volume on startup between 0 and 100
initial_volume = "100"

# If set to true, enables volume normalisation between songs.
volume_normalisation = true

# The normalisation pregain that is applied for each song.
normalisation_pregain = -10

# The port `spotifyd` uses to announce its service over the network.
zeroconf_port = 1234

# The proxy `spotifyd` will use to connect to spotify.
#proxy = "http://proxy.example.org:8080"

# The displayed device type in Spotify clients.
# Can be unknown, computer, tablet, smartphone, speaker, tv,
# avr (Audio/Video Receiver), stb (Set-Top Box), and audiodongle.
device_type = "speaker"

```

Here's the journalctl:
```
jan. 18 07:51:11 fedora-desk spotifyd[5139]: Loading config from "/home/myuser/.config/spotifyd/spotifyd.conf"
jan. 18 07:51:11 fedora-desk spotifyd[5139]: No proxy specified
jan. 18 07:51:11 fedora-desk spotifyd[5139]: Daemonizing running instance
jan. 18 07:51:11 fedora-desk spotifyd[5141]: Detached from shell, now running in background.
jan. 18 07:51:11 fedora-desk spotifyd[5141]: Using alsa volume controller.
jan. 18 07:51:11 fedora-desk systemd[1646]: Starting Cleanup of User's Temporary Files and Directories...
jan. 18 07:51:11 fedora-desk systemd[1646]: systemd-tmpfiles-clean.service: Succeeded.
jan. 18 07:51:11 fedora-desk systemd[1646]: Finished Cleanup of User's Temporary Files and Directories.
jan. 18 07:51:11 fedora-desk spotifyd[5141]: Connecting to AP "gew1-accesspoint-e-brpj.ap.spotify.com:443"
jan. 18 07:51:11 fedora-desk spotifyd[5141]: Authenticated as "[REDACTED]" !
jan. 18 07:51:11 fedora-desk spotifyd[5141]: Caught panic with message: called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by robinvd** [comment] 2021-01-18 19:16
I guess that it might be ‘ cache_path = "cache_directory"’. That there is no cache_directory

**Comment by telometto** [comment] 2021-01-20 11:34
> I guess that it might be ‘ cache_path = "cache_directory"’. That there is no cache_directory

How do I fix this?

**Comment by robinvd** [comment] 2021-01-20 18:36
You can comment out the line

**Comment by telometto** [comment] 2021-01-22 13:38
> You can comment out the line

That worked! Thanks :+1: But now I don't get any sound :/

**Comment by robinvd** [comment] 2021-03-02 16:37
I think it means that the values are not valid. But i dont use alsa so i dont think i can be of much help here

**Closed** 2021-06-12 00:47 UTC
Labels: bug, wontfix
