### ISSUE TITLE
Web API related MPRIS commands stop working after one hour

### ISSUE THREAD

**Issue by hifiberry** [Spotifyd/spotifyd#337] opened 2019-09-27 10:39 UTC
Still using the old 0.2.10 version with MPRIS. There is a process polling information on several MPRIS services (not just spotifyd) that polls every few second.
Changing the polling interval doesn't seem to have an effect on the time that the MPRIS interface stops working. It seems that spotifyd MPRIS is responsive only for about 1 hours.
Changing the polling interval doesn't change anything, it seems that the problem always happens after one hour.

**Comment by SirWindfield** [comment] 2019-09-27 10:47
To clarify: you have written (or use) a process that makes every x seconds a call over dbus and asks spotifyd about some information? What exactly are you pulling each time?

An hour sounds like the interval an access token would have before it becomes invalid. Spotifyd uses them to retrieve Metadata information as well as do some other functionality (like next and previous calls).

Some more information would help :) is there a particular reason why you didn't update to a newer release? v0.2.16 (the lastest) moves away from the spotify web API for some of the dbus commands like next and previous. Those would work without token then.

**Comment by hifiberry** [comment] 2019-09-27 11:47
I wasn't aware that there is a new release with a working MPRIS implementation available. I will have a look at the 0.2.16 version.

An expired access token would explain why this stops after 1 hour.

**Comment by hifiberry** [comment] 2019-09-27 11:52
I'm pulling full metadata and playback state. 
It's used here:
https://github.com/hifiberry/audiocontrol2

**Comment by SirWindfield** [comment] 2019-09-27 12:20
I started re-writing the whole MPris implementation at #324. I hadn’t enough time to implement everything though. The token should refresh itself though. There might be a bug in the refresh logic then. I am currently not at home but can do some testing on the weekend :smile:

**Comment by hifiberry** [comment] 2019-09-30 06:56
Just tried 0.2.16, it immediately crashes:

Sep 30 06:54:51 CX50-Office spotifyd[4737]: 06:54:51 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Sep 30 06:54:51 CX50-Office spotifyd[4737]: 06:54:51 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(BlockingClientInFutureContext, "https://api.spotify.com/v1/me/player")

**Comment by hifiberry** [comment] 2019-09-30 06:57
Is there any other way to access metadata AND control the player locally without using MPRIS?

**Comment by SirWindfield** [comment] 2019-09-30 07:38
>Is there any other way to access metadata AND control the player locally without using MPRIS?

Based on the commands user send to me it looks like it only crashes on properties access. You should be fine when you only use control commands like previous, next, pause, play and stop. There is a work around. Spotifyd exposes a TRACK_ID environment variable. You can set the onevent hook via the cli or config file, pointing to a shell script. It gets called each time a song changes. There is a wiki entry with a script that fires a notification based on that.

**Comment by hifiberry** [comment] 2019-09-30 07:44
The crash shown above happens directly when starting spotifyd. I have disabled the process that polls MPRIS data. However, there are multiple other MPRIS-enabled players running at the same time. Right now I can't use MPRIS with the new release at all, not even for next/pause/...
The only way to locally use next/pause/play right now is MPRIS - correct?

**Comment by SirWindfield** [comment] 2019-09-30 07:47
Yes, correct. Out of interest, does it work if you disable other MPRIS players and only use spotifyd?

**Comment by hifiberry** [comment] 2019-09-30 08:40
Ok, I could isolate the crash to the Bluez MPRIS proxy:
https://github.com/Vudentz/BlueZ/blob/master/tools/mpris-proxy.c

If I stop this one, Spotifyd doesn't crash immediately. 

However, trying to access metadata via MPRIS crashes spotifyd. Therefore the old 0.2.10 release seems to be the most stable at the moment.

**Comment by SirWindfield** [comment] 2019-09-30 08:43
Thanks for the investigation! The metadata access is still a problem that I am currently tackling down :)

**Comment by hifiberry** [comment] 2019-09-30 08:47
Ok, seem that I have to wait for 0.2.17 then ;-)

**Comment by hifiberry** [comment] 2019-10-04 07:54
Just compiled the latest 0.2.18 release from "releases".
It says it is 0.2.17 and still crashes:

/usr/bin/spotifyd -V    
spotifyd 0.2.17

07:50:20 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
07:50:20 [WARN] Unhandled dbus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
07:50:20 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: Error(BlockingClientInFutureContext, "https://api.spotify.com/v1/me/player")

I'll check the current github repo and see if this work, maybe it's a packaging error

**Comment by SirWindfield** [comment] 2019-10-04 08:15
I definitely changed the version in the Cargo file. Probably a packaging error.

**Comment by hifiberry** [comment] 2019-10-04 08:32
Yes, looks like a packaging error. Just cloned the current Git repo and compiled, now version is 0.2.18 and it seems to work :-)
Affected is at least the .tar.gz file in the 0.2.18 release, I din't check the other files

**Comment by SirWindfield** [comment] 2019-10-04 12:46
I messed up a little bit during pushing and therefore had to delete a branch. That might have messed up with the Github Actions. The binaries should be fine as the code gets cloned directly from the branch

**Comment by SirWindfield** [comment] 2019-10-05 16:59
I'll close the issue then. Thanks for your patience.

**Comment by hifiberry** [comment] 2019-10-09 12:48
Ok, my message was not clear. While MPRIS itself is working on the 0.2.18 release, the problem still exists. After 1 hour the daemon stops answering MPRIS requests.

**Comment by SirWindfield** [comment] 2019-10-09 12:51
Ah got you. I’ll reopen this one then. I didn’t write the refresh logic code but I can see if I can spare some time this weekend to debug it.

**Comment by hifiberry** [comment] 2019-10-09 12:52
Not sure if it is happening when music is playing (didn't check this), but it definitely happens if nothing is playing.

**Comment by SirWindfield** [comment] 2019-10-09 15:04
Sorry to bother you again, but I think you missed my edit:


> Just to clarify, it stops responding to web api calls like metadata, doesn’t it? Next and previous still work, do they?

```
qdbus org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
```
This will send the next command for example.

Because if even those methods fail (which don’t use the web api) it’s another problem and not an api token related one.

**Comment by hifiberry** [comment] 2019-10-16 15:38
OK, this is the way for me to reproduce this:

```
while (/bin/true) ;  do 
 sleep 1
 dbus-send --system --print-reply \
    --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 \ 
   org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
 date 
done
```

Just sending a command (Pause) doesn't seem to cause problems:
```
while (/bin/true) ;  do  
 sleep 1
 dbus-send --system  --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 \ 
 org.mpris.MediaPlayer2.Player.Pause
 date
done
```

**Comment by hifiberry** [comment] 2019-10-16 15:47
BTW: I would expect that the player stores the Playback status locally and doesn't require the WebAPI for this.

**Comment by SirWindfield** [comment] 2019-10-16 17:18
It probably stores it somewhere but it could be that the dbus server doesn't have access to the right struct right now. My guts tell me that this might be a bigger refactoring 🤮

**Comment by hifiberry** [comment] 2019-10-17 06:12
Interesting observation: This seems to happen only on PlaybackStatus request, not on Metadata requests

**Comment by SirWindfield** [comment] 2019-10-17 10:34
That’s actually really interesting...

**Comment by hifiberry** [comment] 2019-10-17 11:26
Another thing that might help you fixing this. It seems this only happens if no player is active on this Spotify account.

**Comment by SirWindfield** [comment] 2019-10-17 11:37
I've read that in that case the API returns an empty response but still returns with 200. Maybe either we or rspotify don't process it correctly

**Comment by hifiberry** [comment] 2019-10-17 11:49
That might be a good guess

**Comment by hifiberry** [comment] 2019-10-22 14:01
Any news on this? I would like to help. Unfortunately I really don't understand Rust code :(

**Comment by SirWindfield** [comment] 2019-10-22 14:04
Not really. I haven't looked into it. I'll probably do so on the weekend though :)

Rust code is intimidating at first but gets easier really fast :)

**Comment by hifiberry** [comment] 2019-11-04 13:23
Any news on this? It's performing specifically bad today with playback status changing between playing and stopped while the music is playing all the time:

Nov 04 13:22:03 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: playing
Nov 04 13:22:06 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: playing
Nov 04 13:22:08 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: playing
Nov 04 13:22:10 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: playing
Nov 04 13:22:12 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:15 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:17 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:19 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:21 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:23 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: stopped
Nov 04 13:22:25 RL6000 python3[7561]: ERROR: mpris - state org.mpris.MediaPlayer2.spotifyd: playing

**Comment by SirWindfield** [comment] 2019-11-04 13:27
I could reproduce it, yes. But I have no idea why this is happening. I checked the code multiple times for logic errors in the refresh part but couldn’t find any. I’m clueless :(

**Comment by hifiberry** [comment] 2019-11-04 13:30
Is there any chance to retrieve the state directly from the player? It seems that the WebAPI seems to be a bit unreliable anyway.

**Comment by hifiberry** [comment] 2019-11-04 13:31
Ahh, I see this now with the new 0.2.20 release:
Nov 04 13:21:49 RL6000 spotifyd[7538]: 13:21:49 [INFO] Couldn't fetch metadata from spotify: Err(RateLimited(Some(4)))
Nov 04 13:21:51 RL6000 spotifyd[7538]: 13:21:51 [INFO] Couldn't fetch metadata from spotify: Err(RateLimited(Some(2)))

**Comment by SirWindfield** [comment] 2019-11-04 13:50
Well, that is probably something on `rspotify`'s side that has to get fixed. I'll need to take a closer look though before :)

**Comment by MikaelElkiaer** [comment] 2020-01-11 12:08
Could this be what is either directly or indirectly affecting my `playerctl metadata` - which is empty while the errors are occuring?

**Comment by SirWindfield** [comment] 2020-01-11 13:00
Yes, that is probably the case and wouldn't surprise me at all. The whole MPRIS protocol is kind of wacky right now. I am not that familiar with how the whole DBUS protocol stuff works and don't have a lot of time right now due to finals to thoroughly check what is missing from the implementation that we have.

**Comment by SirWindfield** [comment] 2020-02-07 18:27
I am looking into it right now. This will probably not make it into the next release but rather the one after that.

**Comment by SirWindfield** [comment] 2020-02-08 15:02
Related I think: https://github.com/Spotifyd/spotifyd/issues/503

**Comment by ceuk** [comment] 2020-02-25 19:56
Very likely related to #503 IMO - which issue is best to subscribe to you reckon @SirWindfield?

**Comment by hifiberry** [comment] 2020-02-26 08:05
@ceuk This has nothing to do with #503 They are two completely different issues: 
This happens if rate limiting kicks in, while #503 has to do with some session expiration that happens after a fixed time.

**Comment by ceuk** [comment] 2020-02-26 14:53
@hifiberry oh right, OP just mentions the same `Err(RateLimited(Some(X)))` error. Can't see any mention of session expiration etc in that issue? :confused:

**Comment by hifiberry** [comment] 2020-02-26 14:55
@ceuk: It says: "After 1 hour the daemon stops answering MPRIS requests."

**Comment by hifiberry** [comment] 2020-02-26 14:56
The rateLimit has probably nothing to do with this bug.

**Comment by ceuk** [comment] 2020-02-26 14:56
Ohh I see, I thought you meant the other way around

**Comment by fronbasal** [comment] 2020-03-04 19:40
I am experiencing the same issue when using @hifiberry OS. 
The journal says `Couldn't fetch metadata from spotify: Err(RateLimited(Some(n)))` (n is a random number, < 20 in my case). Is there any workaround?

**Comment by hifiberry** [comment] 2020-03-04 19:43
@fronbasal : This has nothing to do with this bug, but https://github.com/Spotifyd/spotifyd/issues/503

**Comment by SirWindfield** [comment] 2020-03-04 21:57
https://github.com/Spotifyd/spotifyd/issues/503#issuecomment-594877319

**Comment by fronbasal** [comment] 2020-03-10 21:09
Sorry, @hifiberry @SirWindfield. Thank you!

**Comment by woodruffw** [comment] 2021-02-21 21:04
Just another datapoint: I can confirm that this is still present on 0.3.0.

The origin of the MPRIS requests doesn't seem to matter; both `playerctl` and `dbus-send` stop working after about an hour. In my case, *none* of the MPRIS commands (not even `PlayPause`) work until some external activity happens, like starting another Spotify Connect client and connecting it to `spotifyd`.

**Comment by mkoreneff** [comment] 2021-04-15 13:15
I also experience the same dbus issue after about an hour of inactivity. 
Using python `interface.GetAll('org.mpris.MediaPlayer2.Player')`
I receive `ERROR:dbus.proxies:Introspect error on :1.247:/org/mpris/MediaPlayer2: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`
In journalctl I can see `spotifyd[493]: Couldn't fetch metadata from spotify: Err(Unauthorized)`

Once an external client connects to spotifyd as a listening device, the dbus issues seem to be resolved.

**Comment by woodruffw** [comment] 2021-07-14 14:43
I'll attempt to repro this with the latest `spotifyd` this evening.

**Comment by elken** [comment] 2023-05-30 09:20
Still hitting this with 0.3.5

**Comment by eladyn** [comment] 2023-05-30 17:13
@elken If I'm not mistaken, this issue should have been fixed provided the daemon isn't idle (not playing anything) for longer than an hour. Are you also running into this with playback active?

**Comment by elken** [comment] 2023-05-30 19:49
Correct, it'll stop playing music after a song ~ an hour. I think I have an idea, so this _may_ be a PEBCAK.

**Comment by elken** [comment] 2023-05-31 06:26
Seems like this one's a PEBCAK; it was `gpg-agent`. Sorry for the noise!

**Closed** 2023-05-31 12:00 UTC
Labels: bug, help wanted, wontfix
