### ISSUE TITLE
Fetching metadata through mpris sometimes returns an empty array.

### ISSUE THREAD

**Issue by TriaSirax** [Spotifyd/spotifyd#503] opened 2020-02-08 11:53 UTC
---
__EDIT:__
If you encounter rate limit errors, please use your own Spotify client ID by setting an environment variable named `SPOTIFYD_CLIENT_ID`. You can create a client ID [here](https://developer.spotify.com/documentation/general/guides/app-settings/).

~ Sven ([SirWindfield](https://github.com/Spotifyd/spotifyd/commits?author=SirWindfield))

---

Hi, first of all thanks for the great work.

My status bar refreshes every 5 seconds and I'm showing the currently playing music on it. So that means in every 5 seconds I'm fetching metadata data from spotifyd with this command:

dbus-send --print-reply --type=method_call \
    --dest=org.mpris.MediaPlayer2.spotifyd \
    /org/mpris/MediaPlayer2 \
    org.freedesktop.DBus.Properties.GetAll \
    string:org.mpris.MediaPlayer2.Player

But sometimes that returns either an empty array or partial data like just the title or just the artist. Example return value:
.
.
dict entry(
         string "Metadata"
         variant             array [
            ]
      )
.
.

When I run spotifyd with --no-daemon option, it prints this for every failed fetching attempt:

Couldn't fetch metadata from spotify: Err(RateLimited(Some(8)))

And seems like the number inside Some() decreases every  second and when it is 0, I can fetch the data. As I'm guessing from its name it is some kind of a limitation. Why is this happening? Is this something that set intentionally? I don't get this kind of error with the official spotify client.
If is there a way to set this limitation to 5 seconds so that it can sync to my bar, I would really appreciate it.

I'm on kernel version 5.5.2 and using the lastest pre-compiled binary.

**Comment by SirWindfield** [comment] 2020-02-08 15:00
The spotify api is fetched to retrieve data related to the currently playing song. All running daemon instances share a client id, meaning that all current users probably reach the rate limit. 

There might be an alternative way to get the metadata through librespot, but as far as I know, there isn't one right now. 

A fix would be to introduce a config or env variable that users could use to set their own client_id for now.

**Comment by hifiberry** [comment] 2020-02-09 09:11
I don't think it has to do with the other bug, but I've also seen this. Didn't think there was a global client ID. In this case, the problem would be worse the more people are using spotifyd. I think, a configuration option is needed for this.

**Comment by hifiberry** [comment] 2020-02-09 16:50
After some thinking on this, just polling the API for every MPRIS request might not be a good solution at all as it won't scale very well even with multiple client IDs.
As far as I see, librepot seems to have some kind of metadata support already:
https://github.com/librespot-org/librespot/tree/dev/metadata/src
Would it be possible to use these instead of polling the Web API?

**Comment by SirWindfield** [comment] 2020-02-09 18:08
I think that API is relatively new as at the time of writing that part of code librespot wasn't able to provide metadata.

**Comment by hifiberry** [comment] 2020-02-10 07:29
Do you think this could be used? If spotifyd becomes more popular, rate limits polling the API will become more and more a problem.

**Comment by roqueeee** [comment] 2020-02-19 19:50
The rate limiting also occurs when trying to play a song with 'playerctl open "URI"'. 

The track is never played, journalctl shows the 'Couldn't fetch metadata from spotify: Err(RateLimited(Some(n)))' error.

**Comment by Aimmig** [comment] 2020-02-20 13:59
I'm using spotifyd with playerctl and somehow if the metadata couldn't be fetched, playerctl changes its status to stopped which is quite confusing.

**Comment by SirWindfield** [comment] 2020-03-04 21:57
I think this has been fixed by #528. If anyone still encounters empty metadata when using __their own__ client id, let me know!

The fix is only on the master branch, so you guys would have to compile it yourself.

**Comment by hifiberry** [comment] 2020-03-05 07:28
Is a new release planned in the next time?

**Comment by SirWindfield** [comment] 2020-03-05 07:50
I couldn't test it long enough and hoped that some people would give it a try with their own client id before I push a new release. I didn't encounter any rate limits though (after around 4 hours of play time in total).

**Comment by tablet-mode** [comment] 2020-03-05 17:40
I had this running with my own client id for almost 8 hours today. I didn't encounter any rate limits, however there still seem to be some issues. For the most part metadata was working fine but intermittently I got some errors:
```Loading <Way Down We Go - Recorded at Spotify Studios NYC> with Spotify URI <spotify:track:3inSmIa388icRdpDi5ecJd>
<Way Down We Go - Recorded at Spotify Studios NYC> loaded
Running "\"/home/notify-spotifyd.sh\"" using "/usr/bin/zsh" with environment variables {"PLAYER_EVENT": "change", "TRACK_ID": "3inSmIa3↷
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)
Couldn't fetch metadata from spotify: Err(Unauthorized)

... a few more repeats of the "Couldn't fetch metadata line ...

Couldn't fetch metadata from spotify: Err(Unauthorized)
Loading <Mr. Jones - Live At Chelsea Studios, New York/1997> with Spotify URI <spotify:track:0pjOjoHMJrerHhiXNRs3GK>
Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Unhandled DBus message: (Signal, Some("/org/freedesktop/DBus"), Some("org.freedesktop.DBus"), Some("NameAcquired"))
Unhandled DBus message: (Error, None, None, None)
<Mr. Jones - Live At Chelsea Studios, New York/1997> loaded
```
Over the course of the time I had spotifyd running I had this show up twice.
During these error blocks `playerctl metadata` did not return anything.

**Comment by varac** [comment] 2020-03-07 23:40
I can confirm I don't get any rate limit errors anymore with latest master and own client id.

**Comment by varac** [comment] 2020-03-08 21:11
Another thing I noticed is that after restarting spotifyd, querying the mpris player metatdata times out after 25s (tried with `playerctl metadata` as well as with `dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotifyd /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'`).
Only after playing the first song you can query metadata.

**Comment by theel0ja** [comment] 2020-03-23 02:52
I think the data should be cached while the same track is playing as currently the MPRIS metadata interface is buggy due to ratelimit from Spotify.

**Comment by hifiberry** [comment] 2020-03-23 05:33
@theel0ja I agree on this. Unfortunately I have no experience in Rust and can't help with this.

**Comment by ruifm** [comment] 2020-03-26 11:17
I'm experiencing the same issue. I can only fetch MPRIS metadata using `playerctl metadata` or this [polybar mpris-tail script](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/player-mpris-tail) for a extremely small time window per song.

My `spotifyd` log also shows the [same repeated message](https://github.com/Spotifyd/spotifyd/issues/503#issuecomment-595356352) as @tablet-mode whenever a mprys metadata request was made: 

```
Couldn't fetch metadata from spotify: Err(RateLimited(Some(12)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(4)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(20)))
```

**Comment by AndydeCleyre** [comment] 2020-04-19 18:56
Another log sample:
<details><summary>expand</summary>

```
2020-04-19 14:48:00.981077212  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:04.346346210  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:07.648137851  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:07.863635267  Loading <Saturday Sun> with Spotify URI <spotify:track:1drLQNS9D5z9lBP4DbtO2R>
2020-04-19 14:48:08.351144958  <Saturday Sun> loaded
2020-04-19 14:48:11.179967937  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:14.222461774  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:17.206551892  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:20.367032306  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:23.537730886  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:26.599503936  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:29.731113900  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:32.794865488  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:35.836217514  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:38.908796435  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:41.949998940  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:45.278958916  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:48.775928297  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:51.923958780  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:55.293513117  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:48:58.530899908  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:01.847987917  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:04.891967652  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:08.446911741  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:11.609110250  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:15.003501571  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:17.909110440  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:20.989420724  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:24.163313777  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:27.872548540  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:31.024827866  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:34.008117305  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:37.194799584  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:40.189160523  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:43.933691674  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:47.505853746  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:50.640863101  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:53.757418938  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:56.830607734  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:49:59.903060732  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:02.944090205  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:06.004403835  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:09.216391393  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:12.209174457  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:16.285495303  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:19.298163936  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:22.636325574  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:25.619189116  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:28.918316924  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:31.913478359  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:35.379527245  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:38.873003178  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:42.105541078  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:45.079425937  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:48.198911021  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:51.515567375  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:54.529884695  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:50:57.649242006  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:00.779972153  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:04.161472450  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:07.309188652  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:10.399421967  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:13.649445097  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:16.840252639  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:19.921454977  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:23.052589831  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:26.174395502  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:29.354576632  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:32.376749258  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:35.834713543  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:39.537013413  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:42.696507342  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:45.995336838  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:48.980083099  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:51.971353774  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:55.044410094  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:51:58.104568256  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:01.307261450  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:04.446758264  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:07.695429816  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:10.996238206  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:13.278133664  Loading <Swing Lo Magellan> with Spotify URI <spotify:track:2JtL0a3NHcGkFQ7kfDLKUT>
2020-04-19 14:52:13.710145417  <Swing Lo Magellan> loaded
2020-04-19 14:52:14.179988335  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:17.196625369  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:20.131950469  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:23.136477450  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:26.443582711  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:29.464833319  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:32.529167154  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:35.548996234  Couldn't fetch metadata from spotify: Err(Unauthorized)
2020-04-19 14:52:38.650750682  Couldn't fetch metadata from spotify: Err(Unauthorized)
```

</details>

**Comment by oscarcp** [comment] 2020-05-19 14:31
As you see I linked this issue from another place, but I have something that might be interesting to check. In my case the numbers are not random, to me they look like a request rate limit that is triggered and you have to wait N seconds to be able to query:
```

ec1f9b9cd85047c09580e083795167feCouldn't fetch metadata from spotify: Err(RateLimited(Some(11)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(10)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(10)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(8)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(8)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(6)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(6)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(6)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(4)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(4)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(4)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(2)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(2)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(2)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(1)))
Couldn't fetch metadata from spotify: Err(RateLimited(Some(1)))
```

**Comment by mtshrmn** [comment] 2020-07-25 12:22
Is there any progress on this issue? I'm having the same log output as @oscarcp

**Comment by SirWindfield** [comment] 2020-07-25 12:26
I'm 100% sure the rate limit error is gone if you use your own client ids, if that is what you are referring to @mtshrmn

**Comment by mtshrmn** [comment] 2020-07-25 12:29
I'm using my own client id though

**Comment by mtshrmn** [comment] 2020-07-25 12:35
Just to be sure, the way I should set the client id is by setting the CLIENT_ID variable, right?
taken from #507

**Comment by SirWindfield** [comment] 2020-07-25 12:38
No, `SPOTIFYD_CLIENT_ID`.

**Closed** 2020-07-25 12:41 UTC
Labels: advice, bug

**Comment by evrardjp** [comment] 2020-11-18 08:59
@SirWindfield how do I configure the secret with that `SPOTIFY_CLIENT_ID`? Could you explain that in the top post, please?

**Comment by robinvd** [comment] 2020-11-18 11:22
@evrardjp i dont think you need the secret

**Comment by busybox11** [comment] 2021-04-29 09:27
Hey,
I'm writing a polybar module with spotifyd's MPRIS display on it.
![image](https://user-images.githubusercontent.com/29630035/116529879-b00fdb00-a8dd-11eb-9970-f57423f7e358.png)

I have this rate limiting problem too. Sometimes `playerctl` returns `No player could handle this command` (see screenshot below) and checking the logs of spotifyd tells that I'm rate limited.
![image](https://user-images.githubusercontent.com/29630035/116529950-c453d800-a8dd-11eb-9bce-7816bd6cb80e.png)

Is there any workaround? I tried waiting 2 seconds between each call but it doesn't seem to work.

Here's mo polybar script:
```bash
zscroll -l 35 \
	--delay 0.15 \
	--update-check true "playerctl -p spotifyd metadata --format '{{ title }} - {{ artist }}'" &

sleep 3
wait
```

Thanks in advance!
