### ISSUE TITLE
Unable to loop single track

### ISSUE THREAD

**Issue by xero-lib** [Spotifyd/spotifyd#1115] opened 2022-09-10 17:47 UTC
**Description**
Attempting to set loop to "Track" in multiple UIs fails.

**To Reproduce**
1: Start spotifyd
2: Switch to spotifyd in spotify-tui or the official Spotify client
3: Attempt to enable loop single track (ctrl-r in spt)
4: If the icon doesn't appear to have switched back, wait for current track to end, and it will not loop
**Expected behavior**
Track will loop continuously
**Logs**
<details><summary></summary>

```
<!-- PLEASE PASTE YOUR LOGS BELOW THIS LINE WHEN REPORTING BUGS. Make sure to run spotifyd using the `--verbose` flag -->
Loading config from "/home/helix/.config/spotifyd/spotifyd.conf"
CliConfig { config_path: None, no_daemon: true, verbose: true, pid: None, shared_config: SharedConfigValues { username: Some("taken out for privacy"), username_cmd: None, password: None, password_cmd: Some("taken out for privacy"), use_keyring: false, use_mpris: None, on_song_change_hook: None, cache_path: None, no-audio-cache: false, backend: Some(PulseAudio), volume_controller: None, device: None, control: None, mixer: None, device_name: Some("vega-spotifyd"), bitrate: Some(Bitrate320), initial_volume: None, volume_normalisation: false, normalisation_pregain: None, zeroconf_port: None, proxy: None, device_type: Some(Computer) } }
Found user shell: Some("/bin/fish")
No password specified. Checking password_cmd
Running "pass spotify.com" using "/bin/fish"
No proxy specified
registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
Using software volume controller.
registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
Zeroconf server listening on 0.0.0.0:33737
registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
registering event source with poller: token=Token(3), interests=READABLE | WRITABLE
Connecting to AP "ap.spotify.com:443"
found interface Interface { name: "enp3s0", addr: V4(Ifv4Addr { ip: 192.168.0.14, netmask: 255.255.255.0, broadcast: Some(192.168.0.255) }) }
found interface Interface { name: "enp3s0", addr: V6(Ifv6Addr { ip: 2603:8080:2801:1400::d, netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff, broadcast: None }) }
found interface Interface { name: "enp3s0", addr: V6(Ifv6Addr { ip: 2603:8080:2801:1400:53aa:b0d0:90d5:a318, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
sending packet to 224.0.0.251:5353
found interface Interface { name: "enp3s0", addr: V4(Ifv4Addr { ip: 192.168.0.14, netmask: 255.255.255.0, broadcast: Some(192.168.0.255) }) }
found interface Interface { name: "enp3s0", addr: V6(Ifv6Addr { ip: 2603:8080:2801:1400::d, netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff, broadcast: None }) }
found interface Interface { name: "enp3s0", addr: V6(Ifv6Addr { ip: 2603:8080:2801:1400:53aa:b0d0:90d5:a318, netmask: ffff:ffff:ffff:ffff::, broadcast: None }) }
sending packet to [ff02::fb]:5353
received packet from 192.168.0.14:5353
received packet from 192.168.0.14:5353 with no query
received packet from [fe80::b598:fa62:4195:df79%2]:5353
received packet from [fe80::b598:fa62:4195:df79%2]:5353 with no query
registering event source with poller: token=Token(4), interests=READABLE | WRITABLE
writing; remaining=152
Authenticated as "redacted" !
new Session[0]
Session[0] strong=3 weak=1
Country: "US"
new Spirc[0]
canonical_username: redacted
new Player[0]
Using PulseAudio sink with format: S16
new MercuryManager
writing; remaining=11
input volume:65535 to mixer: 65535
command=AddEventSender
command=VolumeSet(65535)
subscribed uri=hm://remote/user/redacted/ count=0
registering event source with poller: token=Token(5), interests=READABLE
received packet from 192.168.0.12:5353
received question: IN _googlezone._tcp.local
received packet from 192.168.0.12:5353
received question: IN _googlezone._tcp.local
kMessageTypeLoad "" webapi-700f3144924b47f9a1f677e729d880bb 678569815 1662830907471 kPlayStatusPlay
State: index: 2 position_ms: 59 status: kPlayStatusPlay position_measured_at: 1662830912674 context_description: "" shuffle: false repeat: false playing_from_fallback: true row: 0 playing_track_index: 2 track {gid: "9\272\255\311WLEj\275\331\233\210\363{To"} track {gid: "\377\377t\316\036\246@*\265k\t\203q`\254\321"} track {gid: "\356\212VYp,J\\\277&\316\373$\0011\252"} track {gid: "\001\301\014\0309fGL\231y\t\255\205\205\025\237"} track {gid: "\375z\263\314FRO\030\231\332\340\353\266\367\n="} track {gid: "\366\217\370\311\322`Fj\275\\\204G:S6\376"} track {gid: "YJ\023\315\244\257I\352\234 c\033\032s\374\240"} track {gid: "\301q\2201\323\036O\r\216\362Gp\001A\222~"} track {gid: "ec1\312\3330AC\232\013v\257LDZ\203"} track {gid: "U\232\333u\240\331D\312\235\207\036\021'\017\341\030"} track {gid: "H\314\306\212\240\301C\364\200\345g\353La\301}"} track {gid: "\343|}c\225\346F\301\244\374\030o\207\213\361B"} track {gid: "hx\305\322\274?OZ\216\247\330\267\203\346N\004"} track {gid: "M\231z+R\320A\265\264\025\364\035\355\217 \233"} track {gid: "\331WD\362\226\360LS\202,5\354uZ \244"} track {gid: "\355j\034kn$C\252\273!/\232q\247\306T"} track {gid: "?\007\312\323\254.DL\242\335|\352\214\311\0109"}
Frame has 17 tracks
Sending status to server: [kPlayStatusPlay]
command=Load(SpotifyId { id: 317074551336536026779073596733459083690, audio_type: Track }, true, 59)
Sending status to server: [kPlayStatusPlay]
writing; remaining=1518
writing; remaining=83
Loading <INBETWEEN> with Spotify URI <spotify:track:7g7or6ba1mBgq5Ydj2ixjs>
Downloading file 8a663088ddfd8435cc0985169c66ecc937980c4e
new ChannelManager
new AudioKeyManager
writing; remaining=49
Ping time estimated as: 70 ms.
Normalisation Data: NormalisationData { track_gain_db: -8.157713, track_peak: 1.072335, album_gain_db: -10.078444, album_peak: 1.1562074 }
Normalisation Type: Album
Normalisation Threshold: 0.0
Normalisation Method: Dynamic
Normalisation Factor: 0.31338474
Normalisation Attack: 0.005
Normalisation Release: 0.1
Normalisation Knee: 1.0
Ping time estimated as: 54 ms.
Ping time estimated as: 53 ms.
<INBETWEEN> (114845 ms) loaded
== Starting sink ==
Sending status to server: [kPlayStatusPlay]
==> kPlayStatusPlay
writing; remaining=759
writing; remaining=106
Ping time estimated as: 56 ms.
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received question: IN _%9E5E7C8F47989526C9BCD95D24084F6F0B27C5ED._sub._googlecast._tcp.local
received question: IN _233637DE._sub._googlecast._tcp.local
received question: IN _googlecast._tcp.local
received packet from 192.168.0.12:5353
received packet from 192.168.0.12:5353 with no query
received packet from 192.168.0.12:5353
received packet from 192.168.0.12:5353 with no query
received packet from 192.168.0.30:5353
received packet from 192.168.0.30:5353 with no query
received packet from 192.168.0.30:5353
received packet from 192.168.0.30:5353 with no query
received packet from 192.168.0.29:5353
received packet from 192.168.0.29:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received question: IN Bitdefender for Android._bitdefender-app._tcp.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received question: IN Android-29.local
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
kMessageTypeRepeat "" webapi-700f3144924b47f9a1f677e729d880bb 678576065 1662830913541 kPlayStatusPlay
Sending status to server: [kPlayStatusPlay]
writing; remaining=759
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
kMessageTypeRepeat "" webapi-700f3144924b47f9a1f677e729d880bb 678577766 1662830918914 kPlayStatusPlay
Sending status to server: [kPlayStatusPlay]
writing; remaining=759
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
File 8a663088ddfd8435cc0985169c66ecc937980c4e complete
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
received packet from 192.168.0.18:5353
received packet from 192.168.0.18:5353 with no query
received packet from [fe80::80f5:f558:3510:e1b%2]:5353
received packet from [fe80::80f5:f558:3510:e1b%2]:5353 with no query
kMessageTypeRepeat "" webapi-700f3144924b47f9a1f677e729d880bb 678594160 1662830920665 kPlayStatusPlay
Sending status to server: [kPlayStatusPlay]
writing; remaining=759
received packet from 192.168.0.18:5353
received question: IN _%9E5E7C8F47989526C9BCD95D24084F6F0B27C5ED._sub._googlecast._tcp.local
received question: IN _233637DE._sub._googlecast._tcp.local
received question: IN _googlecast._tcp.local
received packet from 192.168.0.12:5353
received packet from 192.168.0.12:5353 with no query
received packet from 192.168.0.12:5353
received packet from 192.168.0.12:5353 with no query
received packet from 192.168.0.30:5353
received packet from 192.168.0.30:5353 with no query
received packet from 192.168.0.29:5353
received packet from 192.168.0.29:5353 with no query
received packet from 192.168.0.30:5353
received packet from 192.168.0.30:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
received packet from 192.168.0.31:5353
received packet from 192.168.0.31:5353 with no query
drop Spirc[0]
Shutting down player thread ...
drop PlayerInternal[0]
PlayerInternal thread finished.
drop Session[0]
drop AudioKeyManager
drop ChannelManager
deregistering event source from poller
deregistering event source from poller
Shutting down discovery server
drop MercuryManager
deregistering event source from poller
drop Dispatch
deregistering event source from poller
deregistering event source from poller

<!-- They have to be betwenn the `/summary` and the `/details` HTML tags, and inside the backticks '`' -->  
```

</details>

**Compilation flags** 
- [ ] dbus_mpris
- [ ] dbus_keyring
- [x] alsa_backend
- [ ] portaudio_backend
- [ ] pulseaudio_backend
- [ ] rodio_backend

**Versions (please complete the following information):**

- OS: Arch Linux 5.19.4-arch1-1
- Spotifyd: spotifyd 0.3.3
- cargo: cargo 1.62.0 (a748cf5a3 2022-06-08)

Notes: had to remove tens of thousands of lines of "frame decoded from buffer" and "attempting to decode a frame" and "flushing framed transport" and "framed transport flushed" because with them it was too long for an issue and exceeded GitHubs character limit of 65536.

**Comment by eladyn** [comment] 2022-09-11 12:01
Hi and thank you for the report!

I suppose, this is more or less the same as [this issue](https://github.com/Spotifyd/spotifyd/issues/1071). Can you confirm that?

**Comment by eladyn** [comment] 2022-10-02 12:54
Closing as duplicate of #1071.

**Closed** 2022-10-02 12:55 UTC
Labels: bug, duplicate
