### ISSUE TITLE
Create binaries for aarch64 (eg. for Raspberry PI 4)

### ISSUE THREAD

**Issue by toabctl** [Spotifyd/spotifyd#613] opened 2020-06-17 16:17 UTC
It's great that you already provide [prebuilt binaries](https://github.com/Spotifyd/spotifyd/releases) but binaries for ARM 64-bit (aarch64 or arm64) are missing. Would be cool to have those binaries.

**Comment by SirWindfield** [comment] 2020-06-17 16:36
Duplicate of https://github.com/Spotifyd/spotifyd/issues/280

**Closed by SirWindfield** 2020-06-17 16:36 UTC
Labels: enhancement
