### ISSUE TITLE
DBus query hangs, requires restart.

### ISSUE THREAD

**Issue by blueForestIcarus** [Spotifyd/spotifyd#567] opened 2020-04-14 02:34 UTC
**Description**
Occasionally, the dbus interface fails to respond, hanging qdbus (or playerctl, etc) untill timeout. It is normally necessary to restart spotifyd at this point. When it happens, the music keeps playing if it was playing before.

**To Reproduce**
I don't know any surefire way to reproduce the bug, as it is intermittent. Likewise I haven't been able to get logs from when it happens. I will add logs once I have reproduced the issue while running spotifyd with --verbose.

**Version**
os: Arch linux.
aur/spotifyd-full 0.2.24-1 
running as systemd user service

**Comment by blueForestIcarus** [comment] 2020-04-14 05:46
logs starting from when I initiate dbus command.

<details> 

> event Readable Token(369098756)
> loop process - 1 events, 0.000s
> event Readable Token(369098756)
> loop process - 1 events, 0.000s
> event Readable Token(369098756)
> loop process - 1 events, 0.000s
> D-Bus i/o poll ready: 28 is Ready(Readable)
> D-Bus i/o unix ready: 28 is Readable | Aio
> event Readable Token(369098756)
> loop process - 1 events, 0.000s
> handle_msgs: (MethodCall, Some("/org/mpris/MediaPlayer2"), Some("org.freedesktop.DBus.Introspectable"), Some("Introspect"))
> loop poll - 3.99089363s
> loop time - Instant { tv_sec: 362030, tv_nsec: 514818994 }
> loop process, 8.941µs
> D-Bus i/o poll ready: 28 is Ready(Readable)
> D-Bus i/o unix ready: 28 is Readable | Aio
> scheduling Read for: 4
> loop poll - 23.58µs
> loop time - Instant { tv_sec: 362030, tv_nsec: 514856624 }
> loop process, 7.365µs
> event Readable | Writable Token(4194305)
> event Readable | Writable Token(8388610)
> loop process - 2 events, 0.000s
> received packet from V4(192.168.45.34:5353)
> received packet from V4(192.168.45.34:5353)
> scheduling Read for: 1
> scheduling Read for: 1
> received packet from V6([fe80::34e5:7725:4482:4bc1]:5353)
> received packet from V6([fe80::34e5:7725:4482:4bc1]:5353)
> scheduling Read for: 2
> scheduling Read for: 2
> loop poll - 515.443422ms
> loop time - Instant { tv_sec: 362031, tv_nsec: 30312706 }
> loop process, 93.798µs
> scheduling Read for: 1
> scheduling Read for: 2
> loop poll - 70.396µs
> loop time - Instant { tv_sec: 362031, tv_nsec: 30506394 }
> loop process, 39.733µs
> event Readable | Writable Token(4194305)
> loop process - 1 events, 0.000s
> received packet from V4(192.168.0.106:5353)
> received packet from V4(192.168.0.106:5353) with no query
> scheduling Read for: 1
> scheduling Read for: 1
> scheduling Read for: 2
> loop poll - 101.113359ms
> loop time - Instant { tv_sec: 362031, tv_nsec: 131680313 }
> loop process, 82.601µs
> event Readable | Writable Token(4194305)
> loop process - 1 events, 0.000s
> event Readable | Writable Token(8388610)
> event Readable | Writable Token(4194305)
> loop process - 2 events, 0.000s
> received packet from V4(192.168.45.34:5353)
> received packet from V4(192.168.45.34:5353)
> scheduling Read for: 1
> scheduling Read for: 1
> received packet from V6([fe80::34e5:7725:4482:4bc1]:5353)
> received packet from V6([fe80::34e5:7725:4482:4bc1]:5353)
> scheduling Read for: 2
> scheduling Read for: 2
> loop poll - 921.953144ms
> loop time - Instant { tv_sec: 362032, tv_nsec: 53758866 }
> loop process, 49.251µs
> event Readable | Writable Token(4194305)
> loop process - 1 events, 0.000s
> received packet from V4(192.168.0.106:5353)
> received packet from V4(192.168.0.106:5353) with no query
> scheduling Read for: 1
> scheduling Read for: 1
> scheduling Read for: 2
> loop poll - 101.107547ms
> loop time - Instant { tv_sec: 362032, tv_nsec: 154947897 }
> loop process, 48.994µs
> event Readable | Writable Token(4194305)
> loop process - 1 events, 0.000s
> event Readable | Writable Token(4194305)
> loop process - 1 events, 0.000s
> received packet from V4(192.168.0.1:58581)
> received packet from V4(192.168.0.1:37218)
> received packet from V4(192.168.0.1:60450)
> received packet from V4(192.168.0.1:56797)
> received packet from V4(192.168.0.1:57609)
> received packet from V4(192.168.0.1:53735)
> scheduling Read for: 1
> scheduling Read for: 1
> scheduling Read for: 2
> loop poll - 3.790423152s
> loop time - Instant { tv_sec: 362035, tv_nsec: 945466038 }
> loop process, 50.051µs
> 

<summary> expand </summary></details>

**Comment by hifiberry** [comment] 2020-04-19 05:53
This is a duplicate of https://github.com/Spotifyd/spotifyd/issues/337

**Comment by deisi** [comment] 2020-05-01 08:17
This can be solved by self compiling from current master branch. I have not experienced this since then.

**Closed** 2021-01-23 15:54 UTC
Labels: bug, wontfix
