### ISSUE TITLE
[BUG] Player thread panicked. Macos BigSur

### ISSUE THREAD

**Issue by Tintef** [Spotifyd/spotifyd#752] opened 2021-01-08 21:59 UTC
**Description**

After installing `spotifyd` using brew (both normal and head: `brew install spotifyd` and `brew install spotifyd --head`) and setting my config I get the following error when trying to play a song from `spotify-tui`:

```
Caught panic with message: attempted to zero-initialize type `librespot_tremor::tremor_sys::ov_callbacks`, which is invalid
```

Here's my config file:
```
[global]
username = "********"
password = "********"

device_name = "********"
device_type = "computer"

backend = "rodio"
volume_controller = "softvol"
bitrate = 320

cache_path = "/Users/<username>/Library/Application Support/Spotify/PersistentCache/Storage"
no_audio_cache = false

volume_normalisation = true
normalisation_pregain = -10

zeroconf_port = 1234
```

**To Reproduce**
Not sure if it's easy to reproduce 😞  I'll list my versions below.

**Expected behavior**
No error on the terminal and music plays 😄 

**Logs**
<details><summary>Click to show logs</summary>
> RUST_BACKTRACE=1 spotifyd --no-daemon<br />
    Loading config from "/Users/<username>/.config/spotifyd/spotifyd.conf"<br />
    No proxy specified<br />
    Using software volume controller.<br />
    Failed to register IPv6 receiver: Os { code: 49, kind: AddrNotAvailable, message: "Can\'t assign requested address" }<br />
    Connecting to AP "guc3-accesspoint-b-s9w6.ap.spotify.com:443"<br />
    Authenticated as "*********" !<br />
    Country: "UY"<br />
    Loading <Manfreddi> with Spotify URI <spotify:track:2YXxIa0SM5z3O8POgihI3K><br />
    Caught panic with message: attempted to zero-initialize type `librespot_tremor::tremor_sys::ov_callbacks`, which is invalid<br />
    Caught panic with message: called `Result::unwrap()` on an `Err` value: "SendError(..)"<br />
    Player thread panicked!
</details>

**Versions (please complete the following information):**

- OS: macos bigsur - 11.1
- Spotifyd: 0.2.24
- cargo: 1.48.0

**Additional context**:

I'm willing to build from source and change whatever is necessary to test/debug, I just don't know what to try.

Thanks in advance!

**Comment by JojiiOfficial** [comment] 2021-01-08 22:16
Try to compile it with rust 1.47.0. This is a duplicate of #719.

**Closed by JojiiOfficial** 2021-01-08 22:16 UTC
Labels: bug

**Comment by Tintef** [comment] 2021-01-08 23:04
Thanks
