### ISSUE TITLE
Hide unplayable songs

### ISSUE THREAD

**Issue by Frederick888** [Spotifyd/spotifyd#794] opened 2021-01-23 13:29 UTC
**Is your feature request related to a problem? Please describe.**
Some songs in my playlists are unplayable. It causes errors when client tries to play such songs.

**Describe the solution you'd like**
Implementing a 'Hide Unplayable Songs' option like the official Spotify app.
![File 24-1-21, 00 28 43](https://user-images.githubusercontent.com/4507647/105579496-37c7e400-5ddb-11eb-9adf-5ada67874927.jpeg)

**Describe alternatives you've considered**
Deleting those songs from my playlist.

**Comment by JojiiOfficial** [comment] 2021-01-23 16:59
There is no such thing as 'hiding songs' since spotifyd doesn't dispay any. If there is a panic/error when playing 'unplayable' songs, please paste it. This is another issue which should be fixed in case its caused by spotifyd.

**Comment by Frederick888** [comment] 2021-01-23 17:31
For example, in one of my playlists the first 3 songs are unplayable.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/4507647/105609279-55597580-5dfc-11eb-8269-53a5771b1057.png">

<img width="712" alt="image" src="https://user-images.githubusercontent.com/4507647/105609308-7d48d900-5dfc-11eb-963d-e36a5c88b903.png">

In `spt` if I choose any of them the playback just stops:

```
event Readable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 18.858204492s
loop time - Instant { t: 101897221113932 }
loop process, 21.827µs
kMessageTypeLoad "" webapi-fd53d24a4c1240bbada50df3f1e1a041 809839986 1611422552743
State: context_uri: "spotify:playlist:4BQbhhBMXPR4PZSxIU3tuH" index: 4294967295 position_ms: 0 status: kPlayStatusStop position_measured_at: 1611422575312 context_description: "\345\204\252\343\201\227\343\201\204\346\233\262" shuffle: false repeat: false playing_from_fallback: true
Frame has 0 tracks
No more tracks left in queue
command=Stop
Player::stop called from invalid state
scheduling Read for: 4
flushing framed transport
writing; remaining=439
framed transport flushed
loop poll - 343.224µs
loop time - Instant { t: 101897221753714 }
loop process, 19.373µs
event Readable | Writable Token(16777220)
loop process - 1 events, 0.000s
attempting to decode a frame
frame decoded from buffer
attempting to decode a frame
scheduling Read for: 4
flushing framed transport
framed transport flushed
loop poll - 160.925599ms
loop time - Instant { t: 101897382712130 }
loop process, 19.271µs
loop poll - 5.521µs
loop time - Instant { t: 101897382782498 }
loop process, 15.891µs
```

Is this something should actually be handled by frontend, i.e. `spt`?

**Comment by slondr** [comment] 2021-01-24 03:54
> Is this something should actually be handled by frontend, i.e. `spt`?
Yes.

**Closed** 2021-01-24 03:54 UTC
Labels: enhancement, invalid
