### ISSUE TITLE
Spotifyd prints error, disconnects, but does not exit

### ISSUE THREAD

**Issue by nalt** [Spotifyd/spotifyd#156] opened 2018-07-29 09:22 UTC
My spotifyd repeatedly prints an error message after a few minutes:
"[ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }"

After this message, either (a) spotifyd exists, or (b) playing stops, and the daemon becomes invisible to Spotify apps. Also, spotifyd cannot be killed with Ctrl+C any more. So it does not even react to signals any more. #127 could be related.

Could it help to just handle this connection reset error more gracefully?

**Comment by mikusp** [comment] 2018-07-31 21:12
I am also experiencing this issue on Odroid C2. I'm using systemd unit to manage spotifyd, and after line `[ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }` is printed in `systemctl status spotifyd`, it still reports spotifyd as running, but other Spotify clients won't connect to it and eventually it will be dropped.

I can provide any additional information that will help with resolving this bug.

**Comment by nalt** [comment] 2018-12-29 18:43
The connection errors may be unavoidable in some cases.

The bigger problem is what happed after the connection error: spotifyd sometimes goes into a kind of zombie state, where it does function any more and also does not listen to signals. The process should cleanly exit instead, so it can then be restarted by systemd.

**Comment by zetorian** [comment] 2019-02-21 03:37
I have been experiencing a similar error, but after a suspend.
I suspect it is that the network connection changes after spotifyd is pushed to ram when NetworkManager turns off the connection, killing the socket it was using.

After coming back from suspend, I have the same issue where it just sits in idle, ideally spotifyd would simply just reconnect to the server and continue on with life, but a clean exit would be acceptable as well.

**Comment by theisgroenbech** [comment] 2019-04-01 11:35
I have the same issue. Has it been resolved?

Dell XPS 15 9550 
OS: Ubuntu 16.04
Steps to reproduce:
- download v0.2.5
- run: ./spotifyd  --no-daemon
- play music from phone
- wait 5-6 minutes
- "ConnectionReset"

`13:26:46 [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }`

**Comment by giuliocalzolari** [comment] 2019-08-19 19:45
I have the same issue. do you know why is happening?

Raspberry py
OS: Raspian 8.0
Steps to reproduce:

download v0.2.11
run: spotifyd as systemd
Using alsa volume controller.

"ConnectionReset"
spotifyd[903]: 21:39:09 [ERROR] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

**Comment by SirWindfield** [comment] 2019-09-05 17:03
@giuliocalzolari Do you lose your internet connection? The only thing that will reset the daemon and put it into the zombie state is a failing network connection. This is currently a limitation by `librespot` itself as it doesn't reconnect if the connection drops.
I can take a look if it is possible to detect this and exit the daemon in that case.

**Comment by giuliocalzolari** [comment] 2019-09-05 20:04
No the connection is stable.. I will double check when is going to be resolved in librespot

**Comment by nicokaiser** [comment] 2020-01-16 07:27
Same here. The worst thing is that the daemon does not exit immediately (where it could be restarted by systemd) but enters the mentioned "zombie state".

There is a dirty workaround used by HifiBerry to restart spotifyd on errors https://github.com/hifiberry/hifiberry-os/blob/master/buildroot/package/spotifyd/spotify-watchdog-systemd but this really should not be necessary...

**Comment by SirWindfield** [comment] 2020-02-07 14:33
Note: https://github.com/librespot-org/librespot/pull/427? Not sure

**Comment by jb55** [comment] 2020-02-10 22:35
looks like https://github.com/librespot-org/librespot/pull/427 was released in librespot 0.1.1, going to give it a try and see if it fixes the disconnect issues...

**Comment by SirWindfield** [comment] 2020-02-15 12:15
If someone in this issue still encounters disconnects that do not reconnect by itself, please re-open this issue!

**Comment by paulbastian** [comment] 2020-04-29 09:12
Issue still happening for me :(
my setup is raspberry pi2+arch+alsa+spotifyd version 0.2.24

**Comment by narvalotech** [comment] 2020-04-30 21:44
Issue still happening for me too:
```
Apr 30 15:29:54 orangepipc spotifyd[21525]: <Chalwa> loaded
Apr 30 15:34:32 orangepipc spotifyd[21525]: Loading <Sing And Dance> with Spotify URI <spotify:track:5f66irKP9uXamSCII63ltx>
Apr 30 15:34:33 orangepipc spotifyd[21525]: <Sing And Dance> loaded
Apr 30 15:38:55 orangepipc spotifyd[21525]: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```
Im on armbian + orangepi pc + alsa + spotifyd 0.2.24

**Comment by abrakadabra2k** [comment] 2020-05-08 21:10
Same here :( I really hoped 0.1.1 fixed this issue..
`[2020-05-08T20:27:11Z DEBUG librespot_core::session] Session[0] strong=3 weak=4
[2020-05-08T20:32:10Z DEBUG librespot_connect::spirc] At track 21 of 64 <"spotify:user:1152507199:playlist:18AlLWVdYUhMMrCojluOxr"> update [false]
[2020-05-08T20:32:10Z DEBUG librespot_connect::spirc] Loading context: <spotify:user:1152507199:playlist:18AlLWVdYUhMMrCojluOxr> index: [21] of 64
[2020-05-08T20:32:10Z DEBUG librespot_playback::player] command=Load(SpotifyId { id: 4688000119674851536078536431499049351, audio_type: Track }, true, 0)
[2020-05-08T20:32:10Z DEBUG librespot_core::session] Invalidating session[0]
[2020-05-08T20:32:10Z ERROR librespot_playback::player] Unable to load audio item.
[2020-05-08T20:32:10Z DEBUG librespot_playback::player] drop Player[0]
[2020-05-08T20:32:10Z DEBUG librespot_core::session] drop Dispatch
[2020-05-08T20:32:10Z ERROR librespot_core::session] Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
[2020-05-08T20:32:10Z WARN  librespot] Spirc shut down unexpectedly
[2020-05-08T20:32:10Z DEBUG librespot_connect::spirc] drop Spirc[0]
[2020-05-08T20:32:10Z DEBUG librespot_playback::player] Shutting down player thread ...
[2020-05-08T20:32:10Z DEBUG librespot_core::session] drop Session[0]
`

**Comment by Misterio77** [comment] 2020-06-02 15:51
Also happens with me. Spotifyd 0.2.24 with pulseaudio on desktop pc running arch
```
Jun 02 12:48:40 thanatos spotifyd[94928]: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

**Comment by giuliocalzolari** [comment] 2020-06-02 16:12
@SirWindfield can you re-open this issue

**Comment by aykevl** [comment] 2020-07-07 12:23
Same here. It tends to go in a zombie state but when I hit Ctrl-C it shows an error message:

```
Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```

I have a somewhat unstable internet connection here which sometimes drops for no apparent reason.

**Comment by paulbastian** [comment] 2020-12-05 18:34
Although I don't like running java on a headless raspberry pi, I want to state, that the librespot-java project works flawless and I'm not getting any disconnects there

**Comment by CaptainAsbestos** [comment] 2020-12-20 07:10
i'm encountering this error code as well, running on Mint, Manjaro, and OSX.

**Closed** 2021-03-31 19:55 UTC
Labels: blocked by: librespot, pinned, wontfix

**Comment by HeinrchZurHorstMeyer** [comment] 2021-04-16 20:26
I still have the problem on my RaspberryPi 4 running Raspberry OS Lite.

**Comment by CaptainAsbestos** [comment] 2021-04-18 15:35
> 
> 
> I still have the problem on my RaspberryPi 4 running Raspberry OS Lite.

i returned to the spotifyd config file, and i think the problem was simply that you have to put the username and password for the account between "double quotes" like so. I haven't had the daemon quit out since i did that, so maybe it's just that. Not sure if that works with a keyring or password manager, however.

**Comment by muydipalma** [comment] 2021-06-23 17:18
> Although I don't like running java on a headless raspberry pi, I want to state, that the librespot-java project works flawless and I'm not getting any disconnects there

I want to try this, but, whats wrong with java? i remember my days in windows using matlab and java felt like running a virtualbox, so much resources wasted in emulation.
