### ISSUE TITLE
Caught panic with message: called `Result::unwrap()` on an `Err` value: MercuryError

### ISSUE THREAD

**Issue by stuart12** [Spotifyd/spotifyd#82] opened 2017-10-04 17:41 UTC
hi, spotifyd crashes on a amd64: Linux kooka 4.12.0-1-amd64 #1 SMP Debian 4.12.6-1 (2017-08-12) x86_64 GNU/Linux

Lastest commit 7451cd6ef710e61495cbde468efd66c0a8996011

:; rustc --version
rustc 1.18.0

```
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 85, nanos: 320623995 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 715954156 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable | Writable} Token(12)
17:30:01 [DEBUG] tokio_core::reactor: notifying a task handle
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 110569 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 4816 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 716081607 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(9)
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:342] frame decoded from buffer
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:389] flushing framed transport
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:404] framed transport flushed
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 167367 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 874 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 716260757 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(1)
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 32372 }
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 0
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [DEBUG] librespot::spirc: kMessageTypeHello "Xperia Z3 Tablet Compact Wifi" 2a930d0ca96580788381dd0c6497b2422c0ac11c 122 1507043761073
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 712 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 716399134 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(9)
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:389] flushing framed transport
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:392] writing; remaining=582
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:404] framed transport flushed
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 116040 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 653 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 716527291 }
17:30:01 [DEBUG] tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 25859 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 111789640 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 828353805 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable | Writable} Token(12)
17:30:01 [DEBUG] tokio_core::reactor: notifying a task handle
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 105833 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 5890 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 828483034 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(9)
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:342] frame decoded from buffer
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:389] flushing framed transport
17:30:01 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:404] framed transport flushed
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 194522 }
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 995 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 828691875 }
17:30:01 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(1)
17:30:01 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 38489 }
17:30:01 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:01 [DEBUG] tokio_core::reactor: scheduling direction for: 0
17:30:01 [DEBUG] tokio_core::reactor: blocking
17:30:01 [DEBUG] librespot::spirc: kMessageTypeNotify "47spots" 47spots 440 1507044601520
17:30:01 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 766 }
17:30:01 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004846, tv_nsec: 828831685 }
17:30:01 [DEBUG] tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 26171 }
17:30:13 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 12, nanos: 34408772 }
17:30:13 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004858, tv_nsec: 863279590 }
17:30:13 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable | Writable} Token(6)
17:30:13 [DEBUG] tokio_core::reactor: notifying a task handle
17:30:13 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 148403 }
17:30:13 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 7370 }
17:30:13 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004858, tv_nsec: 863455670 }
17:30:13 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(3)
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 1
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [TRACE] mdns::fsm: [/home/compile/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/c0fc735/src/fsm.rs:76] received packet from V6([2a01:e34:ec11:66e0::1]:5353)
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 2
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 2
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 246754 }
17:30:13 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 1844 }
17:30:13 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004858, tv_nsec: 863721622 }
17:30:13 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable | Writable} Token(6)
17:30:13 [DEBUG] tokio_core::reactor: notifying a task handle
17:30:13 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 61452 }
17:30:13 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 832 }
17:30:13 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004858, tv_nsec: 863799946 }
17:30:13 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(3)
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 1
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [TRACE] mdns::fsm: [/home/compile/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/c0fc735/src/fsm.rs:76] received packet from V6([2a01:e34:ec11:66e0::1]:5353)
17:30:13 [TRACE] mdns::fsm: [/home/compile/.cargo/git/checkouts/rust-mdns-881ed19b93df0e9d/c0fc735/src/fsm.rs:87] received packet from V6([2a01:e34:ec11:66e0::1]:5353) with no query
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 2
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:13 [DEBUG] tokio_core::reactor: scheduling direction for: 2
17:30:13 [DEBUG] tokio_core::reactor: blocking
17:30:13 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 224393 }
17:30:13 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 982 }
17:30:13 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004858, tv_nsec: 864040994 }
17:30:13 [DEBUG] tokio_core::reactor: loop process - 0 events, Duration { secs: 0, nanos: 33197 }
17:30:16 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 2, nanos: 902711604 }
17:30:16 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004861, tv_nsec: 766802694 }
17:30:16 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable | Writable} Token(12)
17:30:16 [DEBUG] tokio_core::reactor: notifying a task handle
17:30:16 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 65835 }
17:30:16 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 3244 }
17:30:16 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004861, tv_nsec: 766879280 }
17:30:16 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(9)
17:30:16 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:16 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:16 [DEBUG] tokio_core::reactor: blocking
17:30:16 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:16 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:342] frame decoded from buffer
17:30:16 [WARN] error 408 for uri 
17:30:16 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:340] attempting to decode a frame
17:30:16 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:16 [DEBUG] tokio_core::reactor: scheduling direction for: 5
17:30:16 [DEBUG] tokio_core::reactor: blocking
17:30:16 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:389] flushing framed transport
17:30:16 [TRACE] tokio_core::io::frame: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/io/frame.rs:404] framed transport flushed
17:30:16 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 110312 }
17:30:16 [DEBUG] tokio_core::reactor: loop poll - Duration { secs: 0, nanos: 519 }
17:30:16 [DEBUG] tokio_core::reactor: loop time - Instant { tv_sec: 2004861, tv_nsec: 766996955 }
17:30:16 [TRACE] tokio_core::reactor: [/home/compile/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-core-0.1.8/src/reactor/mod.rs:295] event Ready {Readable} Token(1)
17:30:16 [DEBUG] tokio_core::reactor: loop process - 1 events, Duration { secs: 0, nanos: 19880 }
17:30:16 [DEBUG] tokio_core::reactor: consuming notification queue
17:30:16 [DEBUG] tokio_core::reactor: scheduling direction for: 0
17:30:16 [DEBUG] tokio_core::reactor: blocking
17:30:16 [ERROR] Caught panic with message: called `Result::unwrap()` on an `Err` value: MercuryError
17:30:16 [DEBUG] librespot::spirc: drop Spirc[0]
17:30:16 [DEBUG] librespot::player: drop Player[0]
17:30:16 [DEBUG] librespot::session: drop Session[0]
17:30:16 [DEBUG] librespot::component: drop AudioKeyManager
17:30:16 [DEBUG] librespot::component: drop AudioFileManager
17:30:16 [DEBUG] librespot::component: drop ChannelManager
17:30:16 [DEBUG] librespot::session: drop Dispatch
```

**Comment by SimonPersson** [comment] 2017-12-19 23:29
Could you try this again on the latest commit?

**Comment by SimonPersson** [comment] 2018-02-23 18:44
I will close this issue. Feel free to reopen if the issue is still there.

**Closed by SimonPersson** 2018-02-23 18:44 UTC
