### ISSUE TITLE
'Divide by zero' when using alsa volume controller

### ISSUE THREAD

**Issue by Askannz** [Spotifyd/spotifyd#70] opened 2017-07-12 02:17 UTC
When setting "volume-control = alsa" in the config file, spotifyd crashes on startup with the error :
`[ERROR] Caught panic with message: attempt to divide by zero`

Works fine with "softvol", though.
Using the latest spotifyd release on Manjaro.

**Comment by flokli** [comment] 2017-07-26 23:37
@Askannz does it still happen to you with the latest master? What version comes with Manjaro?

**Comment by Askannz** [comment] 2017-08-05 01:18
Sorry for hte late reply. I've downloaded spotifyd through the AUR, which pulls it straight from Github, so it should be the latest master.
Tested again today after updating, the problem still occurs.

I don't know much, but it may be an issue with Manjaro itself (since it uses both ALSA and PulseAudio for sound). Softvol works fine so it's no big deal. It's just the error message that is odd.

**Comment by flokli** [comment] 2017-08-08 20:53
I only set `backend` to pulseaudio, (no `volume-control` set), and it doesn't crash.

**Comment by SimonPersson** [comment] 2018-02-23 18:45
I've rewritten the volume controller logic a bit. Can you try on the latest version?

**Comment by flokli** [comment] 2018-02-24 16:46
At least here, `alsa` backend works pretty well now (didn't explicitly set a `mixer`).

**Comment by SimonPersson** [comment] 2018-02-24 17:19
All right, I'll just close this then. Feel free to reopen if the issue is still there!

**Closed by SimonPersson** 2018-02-24 17:19 UTC
Labels: bug
